export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            component: './user/Login',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    path: '/',
    name: '择校系统',
    icon: 'crown',
    routes: [
      {
        name: '综合查询',
        icon: 'table',
        path: '/list',
        component: './TableList',
      },
      {
        name: '综合查询专业版',
        icon: 'table',
        path: '/listPro',
        component: './TableListPro',
        hideInMenu: true,
      },
      {
        name: '自选对比',
        icon: 'table',
        path: '/self_compare',
        component: './SelfCompare',
      },
      {
        name: '专业详情',
        icon: 'table',
        path: '/major_list/',
        component: './MajorList',
        hideInMenu: false,
      },
      {
        name: '院校列表（地区维度）',
        icon: 'table',
        path: '/school_list_by_area',
        component: './SchoolList',
      },
      {
        name: '院校列表（学科排名）',
        icon: 'table',
        path: '/school_list_by_rank',
        component: './SchoolListByRank',
      },
      {
        name: '近4年招生目录查询',
        icon: 'table',
        path: '/zsml',
        component: './ZSML',
      },
      {
        name: '分类排行榜',
        icon: 'table',
        path: '/rank_list/',
        component: './RankList',
      },
      {
        name: '分类排行榜（小红书样式）',
        icon: 'table',
        path: '/rank_list_xhs/',
        component: './RankListXhs',
        hideInMenu: true,
      },
      {
        name: '小红书爆款图文生成工具',
        icon: 'table',
        path: '/ppt_generate/',
        component: './PptGenerate',
        hideInMenu: true,
      },
      {
        name: 'PPT下载',
        icon: 'table',
        path: '/pptGenerate/download/',
        component: './PptList',
        hideInMenu: true,
      },
      {
        name: '院校新闻动态',
        icon: 'table',
        path: '/news_info_list/',
        component: './NewsList',
      },
      {
        name: '普通对比',
        icon: 'table',
        path: '/compare_list',
        component: './CompareTableList',
      },
      {
        name: '学校详情',
        icon: 'table',
        path: '/school_detail/:schoolName',
        component: './SchoolDetail',
        hideInMenu: true,
      },
      {
        name: '报考指导书自动生成',
        icon: 'table',
        path: '/auto_generate/',
        component: './AutoGenerate',
        hideInMenu: true,
      },
      {
        name: '排行榜',
        icon: 'table',
        path: '/rank_page/:rankName',
        component: './RankPage',
        hideInMenu: true,
      },
      {
        name: '小红书排行榜',
        icon: 'table',
        path: '/rank_page/:style/:rankName',
        component: './RankPageXhs',
        hideInMenu: true,
      },
      {
        name: '23学硕变化查询',
        icon: 'table',
        path: '/admission_count_report',
        component: './AdmissionCountReport',
        hideInMenu: true,
      },
      {
        name: '报录比分析',
        icon: 'table',
        path: '/enrollment_rank_list/',
        component: './EnrollmentRankList',
        hideInMenu: true,
      },
      {
        name: '报录比分析报告',
        icon: 'table',
        path: '/enrollment_rank_page/:rankName',
        component: './EnrollmentRankPage',
        hideInMenu: true,
      },
      {
        name: '专业详情具体信息',
        icon: 'table',
        path: '/major_detail/:id',
        component: './MajorDetail',
        hideInMenu: true,
      },
      {
        name: '基本信息综合查询',
        icon: 'table',
        path: '/listFree',
        component: './TableListFree',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/welcome',
    redirect: '/list',
  },
  {
    component: './404',
  },
];
